### ISSUE TITLE
Mangasee search not working

### ISSUE THREAD

**Issue by AzSiAz** [faldez/tanoshi#102]
Hello, thanks for building tanoshi :smile: 

Search in MangaSee does not seem to work currently, maybe because website changed layout ?

**Comment by faldez** [comment]
which version do you use? there is a bug at the extension, you need to use lowercase letters or it won't find anything

**Comment by AzSiAz** [comment]
Latest 0.11.1
And lowercase seem to work, thanks for the workaround :smile:

**Comment by faldez** [comment]
sure, I'll try to fix the bug later
