### ISSUE TITLE
Tanoshi returns 200 on requests to nonexistent URLs

### ISSUE THREAD

**Issue by valderman** [faldez/tanoshi#121]
Tanoshi doesn't return a proper HTTP error when a nonexistent URL is requested. This makes errors harder to catch and debugging harder.

Steps to reproduce:
* Start tanoshi
* Navigate to http://localhost:8080/thisshouldbea404

Expected result:
* Receive an HTTP 404 not found error

Actual result:
* Receive tanoshi front page with HTTP status 200

**Comment by faldez** [comment]
this is actually required to host static files
