### ISSUE TITLE
Features Request : more options and commands acessible from reader

### ISSUE THREAD

**Issue by Bhleg** [faldez/tanoshi#127]
Hi, first thing first, thank you for making Tanoshi, I was looking for a tachiyomi alternative on linux or windows for a long time and you are making it !

while still in developement it is very usable but there is currently a few things that prevent me from using it daily, mainly the lack of commands and options acessible from the reader, in particular :

- a button to toggle fullscreen mode
- the ability to set the reading mode (webtoon, left to right, right ro left)
- the ability to jump to another chapter (something like a drop down menu)

Thank a lot !

**Comment by faldez** [comment]
you are welcome! 

For your requests, I do consider the ability to change reading mode on reader, maybe after the app becomes more stable.
Now, I have questions for point 1, and 3
* if you are using tanoshi from desktop, is fullscreen toggle from browser not enough?
* is going back to detail page from reader is too much click? as far as I know, tachiyomi also don't have this function

**Comment by Bhleg** [comment]
For point 1 : for my concern, no, I use firefox with tree style tab on convertible laptop, to use fullscreen I need to press F11 then proceed to hide the sidebar that dont hide automaticaly, therefore I end up using edge in full screen for reading through Tanoshi.
Now, writing this I perfectly understant that's my problem, I'm using an addon on Firefox on a x86 laptop, I shouldn't expect the ease of use of an touch orientented tablet app.
Nonetheless I think that Fullscreen mode while not striclty speaking necessary for reading, enhance the experience so much more that leaving it execution to each users device is ultimately a disservice for the software, I think youtube illustrate that point very well, you don't expect each user to do the thing themselv, they just press the button on the player.

For point 3 : No it's not, and I just noticed that there is button to in the Top left corner to get back to the chapter list of the manga, I don't now if it was added in the latest release or if I am blind but with this button there is no reason to have a chapter selector in the reader.
My bad.

btw on landscape mode the manga selection (mangadex) feel a bit tiny and [cramped](https://imgur.com/a/R3dtXRA) is this normal ?

English is not my mother tongue so I hoped my points were clear enough.

**Comment by faldez** [comment]
I'll take a look for fullscreen toggle, it shouldn't be too hard to implement

yeah, that is normal, I kinda debating if that's okay, but I decided to just go with it. if that's not okay, maybe I'll change it for the next release

it's okay, english is not my mother tongue either but your points is clear enough

**Comment by faldez** [comment]
Added in #141
