### ISSUE TITLE
Are manga folders supported?

### ISSUE THREAD

**Issue by Luro02** [faldez/tanoshi#169]
Same issue applies: https://github.com/hkalexling/Mango/issues/215

**Comment by Luro02** [comment]
(if you could point me to the parts of the codebase that handle reading the library, I would be willing to fix this issue)

**Comment by faldez** [comment]
this isn't supported for now, but should be an easy fix. local manga are handled in [local.rs](https://github.com/faldez/tanoshi/blob/master/src/local.rs)

**Comment by faldez** [comment]
I'll try to work on this today

**Comment by faldez** [comment]
I've pushed the changes to master, going to take a while to release

**Comment by faldez** [comment]
this is released in v0.25.0
