### ISSUE TITLE
Consider replacing `Box<dyn std::error::Error>` with `anyhow`

### ISSUE THREAD

**Issue by Luro02** [faldez/tanoshi#170]
I would suggest replacing it with [`anyhow`](https://crates.io/crates/anyhow) (which allows you to attach additional context to the errors)

**Comment by faldez** [comment]
nice suggestion. I didn't use `anyhow` before because I tried to reduce dependencies, now that I think of it, reduce one crate doesn't really matter

**Comment by faldez** [comment]
almost all of `Box<dyn std::error::Error>` already replaced with `anyhow` now
