### ISSUE TITLE
Randomly fails to open extension in catalogue

### ISSUE THREAD

**Issue by Luro02** [faldez/tanoshi#175]
The following line is logged:
```
tanoshi    | [2021-08-18T17:18:13Z ERROR tanoshi_vm::extension_thread] receiver dropped
```

and in the frontend this is shown:
![image](https://user-images.githubusercontent.com/24826124/129943652-c7a304b0-ca6b-420f-ad0b-6d6c304877a4.png)

(maybe it would be useful to log the concrete error?) https://github.com/faldez/tanoshi/blob/eab9793a194481faae8205cb56f431809f9bd431/tanoshi-vm/src/vm.rs#L271

**Comment by faldez** [comment]
receiver dropped error mostly come from timeout, it happens when extension thread failed to send data from extension to extension bus, for example this line https://github.com/faldez/tanoshi/blob/eab9793a194481faae8205cb56f431809f9bd431/tanoshi-vm/src/vm.rs#L271

**Comment by faldez** [comment]
since tanoshi dropped wasm extension, this shouldn't happen again
