### ISSUE TITLE
Local Catalogue displays non-comic-book-files

### ISSUE THREAD

**Issue by Luro02** [faldez/tanoshi#189]
![image](https://user-images.githubusercontent.com/24826124/130203355-db4bd072-5a42-4a41-88cd-a349c7349caa.png)

`info.json` is not a valid comic book file, clicking on it triggers `mangaBySourcePath/chapters:11:5: Not a directory (os error 20)`

### How to solve this?

Only display folders and files with the extension: `cb7`, `cba`, `cbr`, `cbt`, `cbz` (extension list is from [Comic book archive Wikipedia article](https://en.wikipedia.org/wiki/Comic_book_archive))

**Comment by faldez** [comment]
huh weird, I do filter the files by their extensions https://github.com/faldez/tanoshi/blob/97d383f863d302dc117c21624f3906b17fec4806/src/local.rs#L42

**Comment by faldez** [comment]
Fixed in https://github.com/faldez/tanoshi/pull/193
