### ISSUE TITLE
"Load More" in local catalogue adds duplicate manga to the list

### ISSUE THREAD

**Issue by Luro02** [faldez/tanoshi#190]
![image](https://user-images.githubusercontent.com/24826124/130203971-9dbe5a0f-1072-4cdb-bea3-38476d5d0e1c.png)
![image](https://user-images.githubusercontent.com/24826124/130204001-7ecca59b-70c1-45d8-b7cc-f9600561696e.png)

**Comment by faldez** [comment]
this should be fixed in https://github.com/faldez/tanoshi/commit/4e4f0bad4233e31061011b5f7dcf46fd3fb45f8f

**Comment by faldez** [comment]
this is released so I'll close the issue
