### ISSUE TITLE
tanoshi-util: Response status type should be `u16`

### ISSUE THREAD

**Issue by Luro02** [faldez/tanoshi#213]
Status codes are not supposed to be negative numbers?

[`reqwest::StatusCode`](https://docs.rs/reqwest/0.11.4/reqwest/struct.StatusCode.html#method.as_u16) wraps around a `u16` which suggests that this would be the correct type.

**Comment by faldez** [comment]
yeah it's supposed to be u16, but because I thought  `Result` can't be serialized I'd use status for result error. But since we know result can be serialized, we can change it to u16

**Comment by faldez** [comment]
tanoshi dropped wasm extension, this isn't being used anymore
