### ISSUE TITLE
open chapter at last page (in continous mode)

### ISSUE THREAD

**Issue by mathroc** [faldez/tanoshi#231]
When I’ve read part of a chapter, I’d like it to open at the last page read when I open it again

**Comment by faldez** [comment]
if you paged reader mode, it should already does this. if it doesn't at all I might need to take look at this

**Comment by mathroc** [comment]
> if you use paged reader mode, it should already does this. if it doesn't at all I might need to take look at this

that’s probably it, I’m using continuous mode

**Comment by faldez** [comment]
yeah, on continuous mode is a bit janky to try to scroll to last page. I might try to add this again, see if I can make it a bit smoother
