### ISSUE TITLE
partially read chapter appears as read

### ISSUE THREAD

**Issue by mathroc** [faldez/tanoshi#232]
It’s not easy to distinguish between fully read and partially read chapter in the chapters list

at the moment a chapter is shown as read as soon as it’s been opened

ps: it might be needed to add a `user_history.full` or similar to indicate that a chapter has been read fully. it’ll probably make it easier to implement filter based on this status. It would also fix the issue in #230 and make it easier than checking if user_history.last_page is the last page of the chapter

**Comment by faldez** [comment]
I thought of displaying number of pages in read progress, so it display `Page:1/12` for example in chapter, or you have another thing in mind?

> at the moment a chapter is shown as read as soon as it’s been opened

as for this, this is a bug. It should only update read progress if you move at least a page.
