### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by baconwaifu** [faldez/tanoshi#265]
Currently, in `routes.rs` you bind explicitly to IPv4 `0.0.0.0` but don't bind to IPv6 at all:
```rust
        let (_, server) = warp::serve(routes).bind_with_graceful_shutdown(([0, 0, 0, 0], $port as u16), async {
```

This works fine in >90% of deployments, as IPv4 is ubiquitous. but most container runtimes support IPv6-only now, and with the rising cost of IPv4 and limited RFC1918 space, more clusters are moving towards IPv6-only, where this doesn't work at all.

A possible solution might be replacing the `[0,0,0,0]` with `IpAddr::from_str("::0")?` as per warp issue [#628](https://github.com/seanmonstar/warp/issues/628#issuecomment-655149763) 
I've built the docker image (which required some updates to the dockerfile to properly integrate `trunk build`) and it seems to work (it now binds to IPv6) but my build seemed to do something weird (`{"data":null,"errors":[{"message":" --> 1:1\n  |\n1 | \n  | ^---\n  |\n  = expected executable_definition","locations":[{"line":1,"column":1}]}]}`) so I can't be confident enough to pull-request it.

**Comment by faldez** [comment]
You're right, I didn't think about ipv6 at all. You can make the PR, maybe I can help see what's wrong with it

**Comment by baconwaifu** [comment]
Actually, scratch that. my change made it bind to *only* IPv6. looks like I need to learn more about `warp` and possibly creating multiple `warp::serve` instances... I'll maintain my branch for now in case anyone wants to use it in an IPv6-only environment though.

**Comment by faldez** [comment]
so I tried using `IpAddr::from_str("::0")?` and it does work using both ipv4 and ipv6.

![image](https://user-images.githubusercontent.com/6511144/134757370-3c5dc49f-407c-4ead-a832-218bfd8f8241.png)
