### ISSUE TITLE
Dockerfile build requires building `tanoshi-web` on the host?

### ISSUE THREAD

**Issue by baconwaifu** [faldez/tanoshi#266]
It's bad form to require that a source-included crate be 'prebuilt' outside the docker build environment, so it would be better to move `tanoshi-web`'s build steps into docker: 

For the builder, install bindgen and the wasm32 target 
```
RUN cargo install trunk wasm-bindgen-cli
RUN rustup target add wasm32-unknown-unknown
```
and then trigger a `trunk build` after the copy but before the `cargo build`
```
RUN cd crates/tanoshi-web; trunk build
```

Unfortunately, I'm having issues with the finished container, which I'm currently debugging (as part of my fix for #265)

**Comment by faldez** [comment]
The problem is, it takes too much time to build tanoshi-web inside docker for multi arch images, on clean build it took nearly 3 hours. Maybe I need two separate Dockerfile? To use inside github action vs outside github action

**Comment by baconwaifu** [comment]
Yeah, cargo is slow. Possibly gate it via --build-arg parameter expansion and shell gates?
like so:
```
ENV BUILD_WEB=${BUILD_WEB:-true}
RUN if [ x${BUILD_WEB} == x"true" ]; do <tanoshi-web build-step>; fi
```
If you pass `--build-arg BUILD_WEB=false` (or any other non-true value) then the shell uses that directly. if undefined, it defaults to "true" via shell variable expansion.

**Comment by faldez** [comment]
that works, better than maintaining two different Dockerfile

**Comment by faldez** [comment]
#267 is merged. I'll close the issue

**Comment by mathroc** [comment]
> The problem is, it takes too much time to build tanoshi-web inside docker for multi arch images, on clean build it took nearly 3 hours without building tanoshi-web. Maybe I need two separate Dockerfile? To use inside github action vs outside github action

If you meant that it would build tanoshi-web for each arch, you can avoid that with `FROM --platform=$BUILDPLATFORM` for the tanoshi-web builder stage and it should be built only once

**Comment by faldez** [comment]
that's interesting. I'll look into it, thanks!
