### ISSUE TITLE
embedded folders incbr or cbz files

### ISSUE THREAD

**Issue by CeskoFTB** [faldez/tanoshi#283]
cbr or cbz files with folders inside are not readable

![Capture](https://user-images.githubusercontent.com/97540714/148979927-4da972ba-5301-48f5-aa01-b418420464d7.PNG)

**Comment by faldez** [comment]
fixed on [2fc3675](https://github.com/faldez/tanoshi/commit/2fc36751c0e2d0a0618ccedd4a67611c8378a2fb)
