### ISSUE TITLE
Feature Request: Ability to disable downloads for non-admin accounts

### ISSUE THREAD

**Issue by Andrewpaps** [faldez/tanoshi#285]
Ability to disable downloads for non-admin accounts so we can share the server with friends without them maliciously creating large folders by downloading multiple files.

**Comment by faldez** [comment]
It's already limited to admin for downloading chapters. is it not the case?

**Comment by Andrewpaps** [comment]
Apologies tried it again just now and it does declare it is forbidden for my non-admin accounts. Potentially a caching issue but likely nothing to worry about.
