### ISSUE TITLE
handle manga with multiple seasons correctly

### ISSUE THREAD

**Issue by mathroc** [faldez/tanoshi#287]
when there is multiple seasons, the next chapter is wrong, the season number seems to be ignored and only the chapter number in the season is taken into account. eg: I'm at season 2 chapter 40, the next chapter link will be to season 1 chapter 41

eg: https://mangasee123.com/manga/Tower-Of-God

**Comment by faldez** [comment]
I think this is more of an issue for nepnep extensions rather than tanoshi, I'll look into it

**Comment by faldez** [comment]
should be fixed on https://github.com/faldez/tanoshi-extensions/commit/c3d1ea03c82c110de694483a7780b75290e6bd5b
