### ISSUE TITLE
[Feature request] Convert manga structure from source

### ISSUE THREAD

**Issue by BirdInFire** [faldez/tanoshi#293]
I want to ask a techical feature to help solve other:

When a manga is downloaded from source (or added into the library), it can generate an entry into your database with a defined template, and the source only populate this template, template who is the same for all sources.

The source only "convert" the manga from the source to the database structure (and so if the source is dead we continue to have the first picture and the data of the manga hitself since in the database).
Like that a FR like : https://github.com/faldez/tanoshi/issues/226 (only change a line "source" into the database).
It let also fix easily this request : https://github.com/faldez/tanoshi/issues/291 (to have multiple source).
Or this one : https://github.com/faldez/tanoshi/issues/292 (to fix error)

**Comment by BirdInFire** [comment]
I add some advantage, for instance if two user read the same manga.

1 all the picture (if downloaded are in the same place),
2 all the metadata are in the same place (database), 
3 if the manga is not downloaded the url of the picture to load (to see the chapter) are already in the database (so not to have to refetch all the picture to load from the source api).
4 if the server go offline the metadata of the manga (is shown(even if we can't read undownloaded manga))

5 THE most important one, it help the dev (you) and the one (like us) who want to contribute to facilitate the source creation, because we have a "template" to populate, and we do not care if our code to populate it is the same or totally different than other source, the goal is to populate it like that the server himself do not care once it's populated.

Many other improvement from the "offline" perspective to the multi user perspective will be better.

**Comment by faldez** [comment]
I don't quite understand what you mean by template, but let me confirm a few things.

when you open a manga of a source, the data is populated into database, unless you refresh the page, it will always get the metadata from database instead of the source.

and if you download the chapter from source, it will get pages from downloaded chapter instead of the source too. what is not is the cover image, it is currently still get from whatever the url from the source. 

but there is workaround for this. you can add the downloaded path directory as local manga, though the history will be different because it's considered different source

**Comment by BirdInFire** [comment]
> I don't quite understand what you mean by template, but let me confirm a few things.
> 
> when you open a manga of a source, the data is populated into database, unless you refresh the page, it will always get the metadata from database instead of the source.
> 
> and if you download the chapter from source, it will get pages from downloaded chapter instead of the source too. what is not is the cover image, it is currently still get from whatever the url from the source.
> 
> but there is workaround for this. you can add the downloaded path directory as local manga, though the history will be different because it's considered different source

have tried to replicate the problem i had but it does not replicate, must be a bug from my browser (picture of the library (who show all the manga)), when the source is not reachable. my bad
