### ISSUE TITLE
FR : Let us restart service or disable auto database creation if missing.

### ISSUE THREAD

**Issue by BirdInFire** [faldez/tanoshi#299]
I actually had a very bad surprise this morning, my docker container have started faster than my disk opening / decryption (by some seconds (after having check in the différents log).

And i had the VERY bad surprise to see that tanoshi in docker have seen no file (system open it) and it was overrited by the startup process of the server, so i HAD to pull the backup, but if i was in dev environement or in (not backup) environnement all my data is wiped without any warning.

And since there isn't any integrated export / import system, it will be nearly impossible to fix without diving into the code to see how it works.

**Comment by faldez** [comment]
interesting, disable database creation if file missing will be useful, since I do need it when trying to deploy on kubernetes. I'll like into it.

also,  portable backup format supposed to be planned.
