### ISSUE TITLE
Sorting of manga in /library not applied on reload

### ISSUE THREAD

**Issue by mathroc** [faldez/tanoshi#303]
in /library if I sort mangas by "Recently read", "descending", and click "save", the mangas are sorted, but when I reload or come back on the library page, the sorting is not applied (but it is remembered: it's still selected in the settings)

(and filter "Unread" but I don't think that's important)

ps: using Firefox on Linux

**Comment by faldez** [comment]
filter read/unread works after reload for me, and yeah sort doesn't work on reload because the values only applied after values changes, my bad.

will fix later

**Comment by mathroc** [comment]
Yes, the filtering works, I just meant that I had a filter active in case there was some kind of conflict

🙏
