### ISSUE TITLE
Default config.yml path may not be working making `--config` flag needed

### ISSUE THREAD

**Issue by eridanired123** [faldez/tanoshi#60]
Can I get confirmation that placing config.yml on the default path works for v0.6.1, please?

`~/.config/tanoshi/config.yml`

I had to indicate the default path with `--config /home/myUser/.config/tanoshi/config.yml` for it to run. Else it would continue throwing `Error: No such file or directory (os error 2)` when simply launching `./tanoshi-linux`.

I double checked that config.yml was on the default path of course.

tanoshi v0.6.1
KDE Neon 5.19 based on Ubuntu Bionic.

**Comment by faldez** [comment]
there was a typo for default config path in the code, this is fixed in v0.7.0, but need to redownload all plugins

**Comment by faldez** [comment]
this should be fixed ini `v0.7.0` but all the extensions need to be updated
