### ISSUE TITLE
Allow update extensions from web interface.

### ISSUE THREAD

**Issue by eridanired123** [faldez/tanoshi#69]
Currently you can install extensions from the web interface only the first time, but once you have installed them and a new version comes up, you can't download them any more and have to do the update manually.

____________
Thanks for this amazing software by the way, I've been using it for a week and even in its _under-heavy-development_ state it has been very comfortable and usable for me, much more than many manga sites out there.

**Comment by faldez** [comment]
yeah it is planned, but I'm still figuring out how to update without restarting the program.
------
Thank you for enjoying it and also for providing feedbacks!

**Comment by faldez** [comment]
included in #92
