### ISSUE TITLE
build guide and extension location

### ISSUE THREAD

**Issue by demolg** [faldez/tanoshi#79]
We need a build guide for tanoshi and extensions so that we can install them with package manager. Therefore we  need also a default directory(such as /usr/share or /usr/lib) to put extensions instead of $HOME/.tanoshi/plugins.

Sorry I'm not a dev, the description is not professional.

**Comment by faldez** [comment]
I don't plan to use package mangar for the extension since package manager is linux only thing, I do plan on make it so you can update extension through the web though

**Comment by faldez** [comment]
Build guide added in readme
