### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by faldez** [faldez/tanoshi#98]

**Comment by 0-Miku-0** [comment]
How can I contact you, do you have discord?, could you assist me with adding dark mode?

**Comment by faldez** [comment]
I have discord, here is my id faldez#8526

**Comment by 0-Miku-0** [comment]
> I have discord, here is my id faldez#8526

I’ve sent a request, my I’d is kazuma#5987

**Comment by faldez** [comment]
added in #109
